(function () {
  var w = window;
  var d = document;

  let k = window.Kapa;
  if (!k) {
    let i = function () {
      i.c(arguments);
    };
    i.q = [];
    i.c = function (args) {
      i.q.push(args);
    };
    window.Kapa = i;
  }

  if (w.__KAPA_WIDGET_LOADED__) return;

  const WEBSITE_ID = "<WEBSITE_ID>";
  const PROJECT_NAME = "<PROJECT_NAME>";
  const PROJECT_COLOR = "<PROJECT_COLOR>";
  const PROJECT_LOGO = "<PROJECT_LOGO>";
  const NATIVE_AI_EXPERIENCE = "<NATIVE_AI_EXPERIENCE>";

  const config = {
    // Required
    WEBSITE_ID: "<WEBSITE_ID>",
    PROJECT_NAME: "<PROJECT_NAME>",
    PROJECT_COLOR: "<PROJECT_COLOR>",
    PROJECT_LOGO: "<PROJECT_LOGO>",

    // General style
    FONT_FAMILY: "<FONT_FAMILY>",

    // Floating widget display
    BUTTON_TEXT: "<BUTTON_TEXT>",
    BUTTON_HIDE: "<BUTTON_HIDE>",
    BUTTON_POSITION_TOP: "<BUTTON_POSITION_TOP>",
    BUTTON_POSITION_BOTTOM: "<BUTTON_POSITION_BOTTOM>",
    BUTTON_POSITION_LEFT: "<BUTTON_POSITION_LEFT>",
    BUTTON_POSITION_RIGHT: "<BUTTON_POSITION_RIGHT>",
    BUTTON_HEIGHT: "<BUTTON_HEIGHT>",
    BUTTON_WIDTH: "<BUTTON_WIDTH>",
    BUTTON_PADDING: "<BUTTON_PADDING>",
    BUTTON_BG_COLOR: "<BUTTON_BG_COLOR>",
    BUTTON_BORDER_RADIUS: "<BUTTON_BORDER_RADIUS>",
    BUTTON_BORDER: "<BUTTON_BORDER>",
    BUTTON_BOX_SHADOW: "<BUTTON_BOX_SHADOW>",
    BUTTON_TEXT_FONT_SIZE: "<BUTTON_TEXT_FONT_SIZE>",
    BUTTON_TEXT_FONT_WEIGHT: "<BUTTON_TEXT_FONT_WEIGHT>",
    BUTTON_TEXT_FONT_FAMILY: "<BUTTON_TEXT_FONT_FAMILY>",
    BUTTON_TEXT_COLOR: "<BUTTON_TEXT_COLOR>",
    BUTTON_TEXT_SHADOW: "<BUTTON_TEXT_SHADOW>",
    BUTTON_ANIMATION_ENABLED: "<BUTTON_ANIMATION_ENABLED>",

    // Modal display
    MODAL_TITLE: "<MODAL_TITLE>",
    MODAL_TITLE_FONT_FAMILY: "<MODAL_TITLE_FONT_FAMILY>",
    MODAL_TITLE_FONT_WEIGHT: "<MODAL_TITLE_FONT_WEIGHT>",
    MODAL_TITLE_FONT_SIZE: "<MODAL_TITLE_FONT_SIZE>",
    MODAL_TITLE_COLOR: "<MODAL_TITLE_COLOR>",
    MODAL_SIZE: "<MODAL_SIZE>",
    MODAL_X_OFFSET: "<MODAL_X_OFFSET>",
    MODAL_Y_OFFSET: "<MODAL_Y_OFFSET>",
    MODAL_BORDER_RADIUS: "<MODAL_BORDER_RADIUS>",
    MODAL_HEADER_MIN_HEIGHT: "<MODAL_HEADER_MIN_HEIGHT>",
    MODAL_HEADER_PADDING: "<MODAL_HEADER_PADDING>",
    MODAL_HEADER_PADDING_TOP: "<MODAL_HEADER_PADDING_TOP>",
    MODAL_HEADER_PADDING_RIGHT: "<MODAL_HEADER_PADDING_RIGHT>",
    MODAL_HEADER_PADDING_BOTTOM: "<MODAL_HEADER_PADDING_BOTTOM>",
    MODAL_HEADER_PADDING_LEFT: "<MODAL_HEADER_PADDING_LEFT>",
    MODAL_HEADER_BG_COLOR: "<MODAL_HEADER_BG_COLOR>",
    MODAL_HEADER_BORDER_BOTTOM: "<MODAL_HEADER_BORDER_BOTTOM>",
    MODAL_BODY_BG_COLOR: "<MODAL_BODY_BG_COLOR>",
    MODAL_BODY_PADDING_TOP: "<MODAL_BODY_PADDING_TOP>",
    MODAL_BODY_PADDING_RIGHT: "<MODAL_BODY_PADDING_RIGHT>",
    MODAL_BODY_PADDING_BOTTOM: "<MODAL_BODY_PADDING_BOTTOM>",
    MODAL_BODY_PADDING_LEFT: "<MODAL_BODY_PADDING_LEFT>",
    MODAL_DISCLAIMER: "<MODAL_DISCLAIMER>",
    MODAL_ASK_AI_INPUT_PLACEHOLDER: "<MODAL_ASK_AI_INPUT_PLACEHOLDER>",
    MODAL_SEARCH_INPUT_PLACEHOLDER: "<MODAL_SEARCH_INPUT_PLACEHOLDER>",
    MODAL_EXAMPLE_QUESTIONS: "<MODAL_EXAMPLE_QUESTIONS>",
    MODAL_IMAGE_HIDE: "<MODAL_IMAGE_HIDE>",
    MODAL_IMAGE_HEIGHT: "<MODAL_IMAGE_HEIGHT>",
    MODAL_IMAGE_WIDTH: "<MODAL_IMAGE_WIDTH>",
    MODAL_WITH_OVERLAY: "<MODAL_WITH_OVERLAY>",
    MODAL_OVERLAY_BG_COLOR: "<MODAL_OVERLAY_BG_COLOR>",
    MODAL_OVERLAY_OPACITY: "<MODAL_OVERLAY_OPACITY>",
    MODAL_INNER_FLEX_DIRECTION: "<MODAL_INNER_FLEX_DIRECTION>",
    MODAL_INNER_JUSTIFY_CONTENT: "<MODAL_INNER_JUSTIFY_CONTENT>",
    MODAL_INNER_MAX_WIDTH: "<MODAL_INNER_MAX_WIDTH>",
    MODAL_INNER_POSITION_RIGHT: "<MODAL_INNER_POSITION_RIGHT>",
    MODAL_INNER_POSITION_LEFT: "<MODAL_INNER_POSITION_LEFT>",
    MODAL_INNER_POSITION_BOTTOM: "<MODAL_INNER_POSITION_BOTTOM>",
    MODAL_Z_INDEX: "<MODAL_Z_INDEX>",
    MODAL_LOCK_SCROLL: "<MODAL_LOCK_SCROLL>",

    // Modal behavior
    MODAL_OVERRIDE_OPEN_CLASS: "<MODAL_OVERRIDE_OPEN_CLASS>",
    MODAL_OPEN_BY_DEFAULT: "<MODAL_OPEN_BY_DEFAULT>",

    // Switch display
    SWITCH_COLOR: "<SWITCH_COLOR>",
    SWITCH_BORDER: "<SWITCH_BORDER>",
    SWITCH_BORDER_RADIUS: "<SWITCH_BORDER_RADIUS>",
    SWITCH_BG_COLOR: "<SWITCH_BG_COLOR>",
    SWITCH_SHOW_ICONS: "<SWITCH_SHOW_ICONS>",

    // User tracking
    USER_ANALYTICS_COOKIE_ENABLED: "<USER_ANALYTICS_COOKIE_ENABLED>",

    // Search mode
    SEARCH_MODE_ENABLED: "<SEARCH_MODE_ENABLED>",
    SEARCH_MODE_DEFAULT: "<SEARCH_MODE_DEFAULT>",
    SEARCH_DISPLAY_NUM_RESULTS: "<SEARCH_DISPLAY_NUM_RESULTS>",
    SEARCH_INCLUDE_SOURCE_NAMES: "<SEARCH_INCLUDE_SOURCE_NAMES>",
    SEARCH_SOURCE_GROUP_ORDER: "<SEARCH_SOURCE_GROUP_ORDER>",
    SEARCH_KEYBOARD_NAV_ENABLED: "<SEARCH_KEYBOARD_NAV_ENABLED>",
    SEARCH_RESULT_HOVER_BG_COLOR: "<SEARCH_RESULT_HOVER_BG_COLOR>",
    SEARCH_RESULT_PRIMARY_TEXT_COLOR: "<SEARCH_RESULT_PRIMARY_TEXT_COLOR>",
    SEARCH_RESULT_SECONDARY_TEXT_COLOR: "<SEARCH_RESULT_SECONDARY_TEXT_COLOR>",
    SEARCH_RESULT_BADGE_BG_COLOR: "<SEARCH_RESULT_BADGE_BG_COLOR>",
    SEARCH_RESULT_BADGE_TEXT_COLOR: "<SEARCH_RESULT_BADGE_TEXT_COLOR>",
    SEARCH_SHOW_MORE_BUTTON_TEXT_COLOR: "<SEARCH_SHOW_MORE_BUTTON_TEXT_COLOR>",
    SEARCH_SHOW_MORE_BUTTON_HOVER_BG_COLOR:
      "<SEARCH_SHOW_MORE_BUTTON_HOVER_BG_COLOR>",
    SEARCH_INPUT_SHOW_ICON: "<SEARCH_INPUT_SHOW_ICON>",
    SEARCH_RESULT_PRIMARY_TITLE_FONT_SIZE:
      "<SEARCH_RESULT_PRIMARY_TITLE_FONT_SIZE>",
    SEARCH_RESULT_SECONDARY_TITLE_FONT_SIZE:
      "<SEARCH_RESULT_SECONDARY_TITLE_FONT_SIZE>",
    SEARCH_ASK_AI_CTA_TEXT_COLOR: "<SEARCH_ASK_AI_CTA_TEXT_COLOR>",
    SEARCH_ASK_AI_CTA_HOVER_TEXT_COLOR: "<SEARCH_ASK_AI_CTA_HOVER_TEXT_COLOR>",
    SEARCH_ASK_AI_CTA_BG_COLOR: "<SEARCH_ASK_AI_CTA_BG_COLOR>",
    SEARCH_ASK_AI_CTA_HOVER_BG_COLOR: "<SEARCH_ASK_AI_CTA_HOVER_BG_COLOR>",
    SEARCH_ASK_AI_CTA_BORDER: "<SEARCH_ASK_AI_CTA_BORDER>",
    SEARCH_ASK_AI_CTA_TEXT_FONT_SIZE: "<SEARCH_ASK_AI_CTA_TEXT_FONT_SIZE>",
    SEARCH_SOURCE_IDS_INCLUDE: "<SEARCH_SOURCE_IDS_INCLUDE>",
    SEARCH_SOURCE_IDS_ORDER: "<SEARCH_SOURCE_IDS_ORDER>",
    SEARCH_RESULT_LINK_TARGET: "<SEARCH_RESULT_LINK_TARGET>",
    SEARCH_SHOW_ASK_AI_CTA: "<SEARCH_SHOW_ASK_AI_CTA>",

    // Localization & Scaling
    LANGUAGE: "<LANGUAGE>",
    SCALE_FACTOR: "<SCALE_FACTOR>",

    // Font sizes
    FONT_SIZE_XS: "<FONT_SIZE_XS>",
    FONT_SIZE_SM: "<FONT_SIZE_SM>",
    FONT_SIZE_MD: "<FONT_SIZE_MD>",
    FONT_SIZE_LG: "<FONT_SIZE_LG>",
    FONT_SIZE_XL: "<FONT_SIZE_XL>",

    // Colors
    HYPERLINK_COLOR: "<HYPERLINK_COLOR>",
    QUESTION_TEXT_COLOR: "<QUESTION_TEXT_COLOR>",
    ANSWER_TEXT_COLOR: "<ANSWER_TEXT_COLOR>",

    // Button enhancements
    BUTTON_HOVER_BG_COLOR: "<BUTTON_HOVER_BG_COLOR>",
    BUTTON_IMAGE: "<BUTTON_IMAGE>",
    BUTTON_IMAGE_HEIGHT: "<BUTTON_IMAGE_HEIGHT>",
    BUTTON_IMAGE_WIDTH: "<BUTTON_IMAGE_WIDTH>",
    BUTTON_Z_INDEX: "<BUTTON_Z_INDEX>",
    BUTTON_HOVER_ANIMATION_ENABLED: "<BUTTON_HOVER_ANIMATION_ENABLED>",

    // Modal general
    MODAL_IMAGE: "<MODAL_IMAGE>",
    MODAL_CLOSE_BUTTON_HIDE: "<MODAL_CLOSE_BUTTON_HIDE>",
    MODAL_DISCLAIMER_BG_COLOR: "<MODAL_DISCLAIMER_BG_COLOR>",
    MODAL_DISCLAIMER_TEXT_COLOR: "<MODAL_DISCLAIMER_TEXT_COLOR>",
    MODAL_DISCLAIMER_FONT_SIZE: "<MODAL_DISCLAIMER_FONT_SIZE>",
    MODAL_FULL_SCREEN: "<MODAL_FULL_SCREEN>",
    MODAL_FULL_SCREEN_ON_MOBILE: "<MODAL_FULL_SCREEN_ON_MOBILE>",
    MODAL_HEADER_LOGO_HIDE_ON_MOBILE: "<MODAL_HEADER_LOGO_HIDE_ON_MOBILE>",
    MODAL_EXAMPLE_QUESTIONS_TITLE: "<MODAL_EXAMPLE_QUESTIONS_TITLE>",
    MODAL_EXAMPLE_QUESTIONS_COL_SPAN: "<MODAL_EXAMPLE_QUESTIONS_COL_SPAN>",
    MODAL_FOOTER: "<MODAL_FOOTER>",

    // Modal behavior
    MODAL_OVERRIDE_OPEN_CLASS_SEARCH: "<MODAL_OVERRIDE_OPEN_CLASS_SEARCH>",
    MODAL_OVERRIDE_OPEN_CLASS_ASK_AI: "<MODAL_OVERRIDE_OPEN_CLASS_ASK_AI>",
    MODAL_OVERRIDE_OPEN_ID: "<MODAL_OVERRIDE_OPEN_ID>",
    MODAL_OVERRIDE_OPEN_ID_SEARCH: "<MODAL_OVERRIDE_OPEN_ID_SEARCH>",
    MODAL_OVERRIDE_OPEN_ID_ASK_AI: "<MODAL_OVERRIDE_OPEN_ID_ASK_AI>",
    MODAL_OVERRIDE_OPEN_SELECTOR: "<MODAL_OVERRIDE_OPEN_SELECTOR>",
    MODAL_OVERRIDE_OPEN_SELECTOR_SEARCH: "<MODAL_OVERRIDE_OPEN_SELECTOR_SEARCH>",
    MODAL_OVERRIDE_OPEN_SELECTOR_ASK_AI: "<MODAL_OVERRIDE_OPEN_SELECTOR_ASK_AI>",
    MODAL_OPEN_ON_COMMAND_K: "<MODAL_OPEN_ON_COMMAND_K>",
    MODAL_COMMAND_K_SEARCH_MODE_DEFAULT: "<MODAL_COMMAND_K_SEARCH_MODE_DEFAULT>",
    MODAL_IMAGE_ASK_AI: "<MODAL_IMAGE_ASK_AI>",
    MODAL_IMAGE_SEARCH: "<MODAL_IMAGE_SEARCH>",
    MODAL_TITLE_SEARCH: "<MODAL_TITLE_SEARCH>",
    MODAL_TITLE_ASK_AI: "<MODAL_TITLE_ASK_AI>",

    // Query input
    QUERY_INPUT_FONT_SIZE: "<QUERY_INPUT_FONT_SIZE>",
    QUERY_INPUT_TEXT_COLOR: "<QUERY_INPUT_TEXT_COLOR>",
    QUERY_INPUT_PLACEHOLDER_TEXT_COLOR: "<QUERY_INPUT_PLACEHOLDER_TEXT_COLOR>",
    QUERY_INPUT_BORDER_COLOR: "<QUERY_INPUT_BORDER_COLOR>",
    QUERY_INPUT_FOCUS_BORDER_COLOR: "<QUERY_INPUT_FOCUS_BORDER_COLOR>",
    SUBMIT_QUERY_BUTTON_BG_COLOR: "<SUBMIT_QUERY_BUTTON_BG_COLOR>",

    // Conversation buttons
    CONVERSATION_BUTTONS_ICONS_ONLY: "<CONVERSATION_BUTTONS_ICONS_ONLY>",

    // Answer copy button
    ANSWER_COPY_BUTTON_HEIGHT: "<ANSWER_COPY_BUTTON_HEIGHT>",
    ANSWER_COPY_BUTTON_WIDTH: "<ANSWER_COPY_BUTTON_WIDTH>",
    ANSWER_COPY_BUTTON_PADDING_X: "<ANSWER_COPY_BUTTON_PADDING_X>",
    ANSWER_COPY_BUTTON_PADDING_Y: "<ANSWER_COPY_BUTTON_PADDING_Y>",
    ANSWER_COPY_BUTTON_BORDER: "<ANSWER_COPY_BUTTON_BORDER>",
    ANSWER_COPY_BUTTON_BORDER_RADIUS: "<ANSWER_COPY_BUTTON_BORDER_RADIUS>",
    ANSWER_COPY_BUTTON_BG_COLOR: "<ANSWER_COPY_BUTTON_BG_COLOR>",
    ANSWER_COPY_BUTTON_HOVER_BG_COLOR: "<ANSWER_COPY_BUTTON_HOVER_BG_COLOR>",
    ANSWER_COPY_BUTTON_TEXT_COLOR: "<ANSWER_COPY_BUTTON_TEXT_COLOR>",
    ANSWER_COPY_BUTTON_FONT_SIZE: "<ANSWER_COPY_BUTTON_FONT_SIZE>",
    ANSWER_COPY_BUTTON_ICON_SIZE: "<ANSWER_COPY_BUTTON_ICON_SIZE>",
    ANSWER_COPY_BUTTON_BOX_SHADOW: "<ANSWER_COPY_BUTTON_BOX_SHADOW>",

    // Thread clear button
    THREAD_CLEAR_BUTTON_HEIGHT: "<THREAD_CLEAR_BUTTON_HEIGHT>",
    THREAD_CLEAR_BUTTON_WIDTH: "<THREAD_CLEAR_BUTTON_WIDTH>",
    THREAD_CLEAR_BUTTON_PADDING_X: "<THREAD_CLEAR_BUTTON_PADDING_X>",
    THREAD_CLEAR_BUTTON_PADDING_Y: "<THREAD_CLEAR_BUTTON_PADDING_Y>",
    THREAD_CLEAR_BUTTON_BORDER: "<THREAD_CLEAR_BUTTON_BORDER>",
    THREAD_CLEAR_BUTTON_BORDER_RADIUS: "<THREAD_CLEAR_BUTTON_BORDER_RADIUS>",
    THREAD_CLEAR_BUTTON_BG_COLOR: "<THREAD_CLEAR_BUTTON_BG_COLOR>",
    THREAD_CLEAR_BUTTON_HOVER_BG_COLOR: "<THREAD_CLEAR_BUTTON_HOVER_BG_COLOR>",
    THREAD_CLEAR_BUTTON_TEXT_COLOR: "<THREAD_CLEAR_BUTTON_TEXT_COLOR>",
    THREAD_CLEAR_BUTTON_FONT_SIZE: "<THREAD_CLEAR_BUTTON_FONT_SIZE>",
    THREAD_CLEAR_BUTTON_ICON_SIZE: "<THREAD_CLEAR_BUTTON_ICON_SIZE>",
    THREAD_CLEAR_BUTTON_BOX_SHADOW: "<THREAD_CLEAR_BUTTON_BOX_SHADOW>",

    // Answer feedback button
    ANSWER_FEEDBACK_BUTTON_HEIGHT: "<ANSWER_FEEDBACK_BUTTON_HEIGHT>",
    ANSWER_FEEDBACK_BUTTON_WIDTH: "<ANSWER_FEEDBACK_BUTTON_WIDTH>",
    ANSWER_FEEDBACK_BUTTON_PADDING_X: "<ANSWER_FEEDBACK_BUTTON_PADDING_X>",
    ANSWER_FEEDBACK_BUTTON_PADDING_Y: "<ANSWER_FEEDBACK_BUTTON_PADDING_Y>",
    ANSWER_FEEDBACK_BUTTON_BORDER: "<ANSWER_FEEDBACK_BUTTON_BORDER>",
    ANSWER_FEEDBACK_BUTTON_ACTIVE_BORDER:
      "<ANSWER_FEEDBACK_BUTTON_ACTIVE_BORDER>",
    ANSWER_FEEDBACK_BUTTON_BORDER_RADIUS:
      "<ANSWER_FEEDBACK_BUTTON_BORDER_RADIUS>",
    ANSWER_FEEDBACK_BUTTON_BG_COLOR: "<ANSWER_FEEDBACK_BUTTON_BG_COLOR>",
    ANSWER_FEEDBACK_BUTTON_ACTIVE_BG_COLOR:
      "<ANSWER_FEEDBACK_BUTTON_ACTIVE_BG_COLOR>",
    ANSWER_FEEDBACK_BUTTON_ACTIVE_HOVER_BG_COLOR:
      "<ANSWER_FEEDBACK_BUTTON_ACTIVE_HOVER_BG_COLOR>",
    ANSWER_FEEDBACK_BUTTON_HOVER_BG_COLOR:
      "<ANSWER_FEEDBACK_BUTTON_HOVER_BG_COLOR>",
    ANSWER_FEEDBACK_BUTTON_TEXT_COLOR: "<ANSWER_FEEDBACK_BUTTON_TEXT_COLOR>",
    ANSWER_FEEDBACK_BUTTON_ACTIVE_TEXT_COLOR:
      "<ANSWER_FEEDBACK_BUTTON_ACTIVE_TEXT_COLOR>",
    ANSWER_FEEDBACK_BUTTON_FONT_SIZE: "<ANSWER_FEEDBACK_BUTTON_FONT_SIZE>",
    ANSWER_FEEDBACK_BUTTON_ICON_SIZE: "<ANSWER_FEEDBACK_BUTTON_ICON_SIZE>",
    ANSWER_FEEDBACK_BUTTON_BOX_SHADOW: "<ANSWER_FEEDBACK_BUTTON_BOX_SHADOW>",

    // CTA button
    CTA_BUTTON_HEIGHT: "<CTA_BUTTON_HEIGHT>",
    CTA_BUTTON_WIDTH: "<CTA_BUTTON_WIDTH>",
    CTA_BUTTON_PADDING_X: "<CTA_BUTTON_PADDING_X>",
    CTA_BUTTON_PADDING_Y: "<CTA_BUTTON_PADDING_Y>",
    CTA_BUTTON_BORDER: "<CTA_BUTTON_BORDER>",
    CTA_BUTTON_BORDER_RADIUS: "<CTA_BUTTON_BORDER_RADIUS>",
    CTA_BUTTON_BG_COLOR: "<CTA_BUTTON_BG_COLOR>",
    CTA_BUTTON_HOVER_BG_COLOR: "<CTA_BUTTON_HOVER_BG_COLOR>",
    CTA_BUTTON_TEXT_COLOR: "<CTA_BUTTON_TEXT_COLOR>",
    CTA_BUTTON_FONT_SIZE: "<CTA_BUTTON_FONT_SIZE>",
    CTA_BUTTON_ICON_SIZE: "<CTA_BUTTON_ICON_SIZE>",
    CTA_BUTTON_BOX_SHADOW: "<CTA_BUTTON_BOX_SHADOW>",

    // Example question button
    EXAMPLE_QUESTION_BUTTON_HEIGHT: "<EXAMPLE_QUESTION_BUTTON_HEIGHT>",
    EXAMPLE_QUESTION_BUTTON_WIDTH: "<EXAMPLE_QUESTION_BUTTON_WIDTH>",
    EXAMPLE_QUESTION_BUTTON_PADDING_X: "<EXAMPLE_QUESTION_BUTTON_PADDING_X>",
    EXAMPLE_QUESTION_BUTTON_PADDING_Y: "<EXAMPLE_QUESTION_BUTTON_PADDING_Y>",
    EXAMPLE_QUESTION_BUTTON_BORDER: "<EXAMPLE_QUESTION_BUTTON_BORDER>",
    EXAMPLE_QUESTION_BUTTON_BORDER_RADIUS:
      "<EXAMPLE_QUESTION_BUTTON_BORDER_RADIUS>",
    EXAMPLE_QUESTION_BUTTON_BG_COLOR: "<EXAMPLE_QUESTION_BUTTON_BG_COLOR>",
    EXAMPLE_QUESTION_BUTTON_HOVER_BG_COLOR:
      "<EXAMPLE_QUESTION_BUTTON_HOVER_BG_COLOR>",
    EXAMPLE_QUESTION_BUTTON_TEXT_COLOR: "<EXAMPLE_QUESTION_BUTTON_TEXT_COLOR>",
    EXAMPLE_QUESTION_BUTTON_FONT_SIZE: "<EXAMPLE_QUESTION_BUTTON_FONT_SIZE>",
    EXAMPLE_QUESTION_BUTTON_BOX_SHADOW: "<EXAMPLE_QUESTION_BUTTON_BOX_SHADOW>",

    // Deep thinking button
    DEEP_THINKING_BUTTON_BG_COLOR: "<DEEP_THINKING_BUTTON_BG_COLOR>",
    DEEP_THINKING_BUTTON_ACTIVE_BG_COLOR:
      "<DEEP_THINKING_BUTTON_ACTIVE_BG_COLOR>",
    DEEP_THINKING_BUTTON_HOVER_BG_COLOR: "<DEEP_THINKING_BUTTON_HOVER_BG_COLOR>",
    DEEP_THINKING_BUTTON_ACTIVE_HOVER_BG_COLOR:
      "<DEEP_THINKING_BUTTON_ACTIVE_HOVER_BG_COLOR>",
    DEEP_THINKING_BUTTON_ACTIVE_HOVER_TEXT_COLOR:
      "<DEEP_THINKING_BUTTON_ACTIVE_HOVER_TEXT_COLOR>",
    DEEP_THINKING_BUTTON_TEXT_COLOR: "<DEEP_THINKING_BUTTON_TEXT_COLOR>",
    DEEP_THINKING_BUTTON_ACTIVE_TEXT_COLOR:
      "<DEEP_THINKING_BUTTON_ACTIVE_TEXT_COLOR>",
    DEEP_THINKING_BUTTON_FONT_SIZE: "<DEEP_THINKING_BUTTON_FONT_SIZE>",
    DEEP_THINKING_BUTTON_ICON_SIZE: "<DEEP_THINKING_BUTTON_ICON_SIZE>",

    // Source links
    SOURCE_LINK_PRIMARY_HEADING_TEXT_COLOR:
      "<SOURCE_LINK_PRIMARY_HEADING_TEXT_COLOR>",
    SOURCE_LINK_SECONDARY_HEADING_TEXT_COLOR:
      "<SOURCE_LINK_SECONDARY_HEADING_TEXT_COLOR>",
    SOURCE_LINK_BORDER: "<SOURCE_LINK_BORDER>",
    SOURCE_LINK_BG_COLOR: "<SOURCE_LINK_BG_COLOR>",
    SOURCE_LINK_HOVER_BG_COLOR: "<SOURCE_LINK_HOVER_BG_COLOR>",

    // Switch enhancements
    SWITCH_LABEL_PADDING_X: "<SWITCH_LABEL_PADDING_X>",
    SWITCH_LABEL_PADDING_Y: "<SWITCH_LABEL_PADDING_Y>",
    SWITCH_LABEL_FONT_SIZE: "<SWITCH_LABEL_FONT_SIZE>",
    SWITCH_LABEL_FONT_WEIGHT: "<SWITCH_LABEL_FONT_WEIGHT>",

    // Behavioral/Functional
    SOURCE_GROUP_IDS_INCLUDE: "<SOURCE_GROUP_IDS_INCLUDE>",
    CONSENT_REQUIRED: "<CONSENT_REQUIRED>",
    CONSENT_SCREEN_TITLE: "<CONSENT_SCREEN_TITLE>",
    CONSENT_SCREEN_DISCLAIMER: "<CONSENT_SCREEN_DISCLAIMER>",
    CONSENT_SCREEN_ACCEPT_BUTTON_TEXT: "<CONSENT_SCREEN_ACCEPT_BUTTON_TEXT>",
    CONSENT_SCREEN_REJECT_BUTTON_TEXT: "<CONSENT_SCREEN_REJECT_BUTTON_TEXT>",
    ANSWER_CTA_BUTTON_ENABLED: "<ANSWER_CTA_BUTTON_ENABLED>",
    ANSWER_CTA_BUTTON_TEXT: "<ANSWER_CTA_BUTTON_TEXT>",
    ANSWER_CTA_BUTTON_LINK: "<ANSWER_CTA_BUTTON_LINK>",
    FOOTER_TOS_PRIVACY_LINKS: "<FOOTER_TOS_PRIVACY_LINKS>",
    KAPA_BRANDING_HIDE: "<KAPA_BRANDING_HIDE>",
    KAPA_BRANDING_TEXT: "<KAPA_BRANDING_TEXT>",
    UNCERTAIN_ANSWER_CALLOUT: "<UNCERTAIN_ANSWER_CALLOUT>",
    USER_SATISFACTION_FEEDBACK_ENABLED: "<USER_SATISFACTION_FEEDBACK_ENABLED>",
    BOT_PROTECTION_MECHANISM: "<BOT_PROTECTION_MECHANISM>",
    USER_ANALYTICS_FINGERPRINT_ENABLED: "<USER_ANALYTICS_FINGERPRINT_ENABLED>",

    // MCP Integration
    MCP_ENABLED: "<MCP_ENABLED>",
    MCP_SERVER_URL: "<MCP_SERVER_URL>",
    MCP_BUTTON_TEXT: "<MCP_BUTTON_TEXT>",
  };

  var l = function () {
    var s = d.createElement("script");
    s.type = "text/javascript";
    s.async = true;
    s.src = "https://widget.kapa.ai/kapa-widget.bundle.js";
    s.setAttribute("data-website-id", WEBSITE_ID);
    s.setAttribute("data-project-name", PROJECT_NAME);
    s.setAttribute("data-project-color", PROJECT_COLOR);
    s.setAttribute("data-project-logo", PROJECT_LOGO);
    s.setAttribute(
      "data-button-hide",
      NATIVE_AI_EXPERIENCE === "true" ? "true" : "false"
    );

    for (const [key, value] of Object.entries(config)) {
      const kebabCaseKey = key.replaceAll("_", "-").toLowerCase();
      if (value !== `<${key}>` && value !== "undefined") {
        s.setAttribute(`data-${kebabCaseKey}`, value);
      }
    }

    var x = d.getElementsByTagName("script")[0];
    x.parentNode.insertBefore(s, x);

    w.__KAPA_WIDGET_LOADED__ = true;

    window.GitBook.registerAssistant({
      label: "Kapa AI",
      icon: "sparkle",
      ui: NATIVE_AI_EXPERIENCE === "true",
      open: (query) => {
        window.Kapa("open", {
          mode: "ai",
          query: query,
          submit: true,
        });
      },
    });
  };
  if (w.attachEvent) {
    w.attachEvent("onload", l);
  } else {
    w.addEventListener("load", l, false);
  }
})();
